# This is used with the label workflow which
# will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# For more information, see:
# https://github.com/actions/labeler

'package: core':
  - changed-files:
    - any-glob-to-any-file:
      - packages/automation-extra/**/*
      - packages/playwright-extra/**/*
      - packages/puppeteer-extra/**/*
      - packages/automation-extra-plugin/**/*
      - packages/puppeteer-extra-plugin/**/*

'plugin: automation-extra':
  - changed-files:
    - any-glob-to-any-file:
      - packages/plugin-*/**/*

'plugin: puppeteer-extra':
  - changed-files:
    - any-glob-to-any-file:
      - packages/puppeteer-extra-plugin-*/**/*

'plugin: recaptcha 🏴':
  - changed-files:
    - any-glob-to-any-file:
      - packages/*recaptcha*/**/*

'plugin: stealth ㊙️':
  - changed-files:
    - any-glob-to-any-file:
      - packages/*stealth*/**/*
