packages:
  - 'packages/*'

overrides:
  fsevents: ^2.1.2
  localtunnel>axios: 1.17.0

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - sharp
  - workerd

allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  workerd: true
