#!/usr/bin/env node

import fs from 'node:fs';
import puppeteer from '@zorilla/puppeteer-extra';
import stealth from '@zorilla/puppeteer-extra-plugin-stealth';
import type { Page } from 'puppeteer';
import { minify } from 'terser';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';

export interface ExtractOptions {
  exclude?: string | string[];
  include?: string | string[];
  list?: boolean;
  minify?: boolean;
}

export function parseArguments(args: string[]): ExtractOptions {
  const argv = yargs(hideBin(args))
    .usage('Usage: $0 [options]')
    .alias('e', 'exclude')
    .describe('e', 'Exclude evasion (repeat for multiple)')
    .alias('i', 'include')
    .describe('i', 'Include evasion (repeat for multiple)')
    .alias('l', 'list')
    .describe('l', 'List available evasions')
    .alias('m', 'minify')
    .describe('minify', 'Minify the output')
    .boolean('m')
    .default('m', true)
    .help('h')
    .alias('h', 'help')
    .parseSync();

  return {
    exclude: argv.exclude as string | string[] | undefined,
    include: argv.include as string | string[] | undefined,
    list: argv.list as boolean | undefined,
    minify: argv.minify as boolean | undefined,
  };
}

export function configureStealthPlugin(
  stealthPlugin: ReturnType<typeof stealth>,
  options: ExtractOptions
): void {
  if (options.exclude) {
    if (typeof options.exclude === 'string') {
      stealthPlugin.enabledEvasions.delete(options.exclude);
    } else {
      options.exclude.forEach(e => {
        stealthPlugin.enabledEvasions.delete(e);
      });
    }
  } else if (options.include) {
    if (typeof options.include === 'string') {
      stealthPlugin.enabledEvasions = new Set([options.include]);
    } else {
      stealthPlugin.enabledEvasions = new Set(options.include);
    }
  }
}

export function createPatchEval(scriptsContainer: { scripts: string }) {
  return function patchEval(this: Page, f: Function, args?: unknown): void {
    // Check if there are options supplied
    if (typeof args !== 'undefined') {
      scriptsContainer.scripts +=
        '(' + f.toString() + ')(' + JSON.stringify(args) + ');\n';
    } else {
      scriptsContainer.scripts += '(' + f.toString() + ')();\n';
    }
  };
}

export async function extractScripts(
  stealthPlugin: ReturnType<typeof stealth>
): Promise<string> {
  const scriptsContainer = { scripts: '' };
  const patchEval = createPatchEval(scriptsContainer);

  // biome-ignore lint/suspicious/noExplicitAny: Type mismatch between puppeteer-extra and puppeteer-extra-plugin declarations
  const browser = await puppeteer.use(stealthPlugin as any).launch({
    headless: true,
  });

  try {
    // Patch evaluateOnNewDocument()
    const page = (await browser.pages()).find(Boolean)!;
    // biome-ignore lint/suspicious/noExplicitAny: Need to patch prototype methods
    (page as any).__proto__.evaluateOnNewDocument = patchEval;
    // biome-ignore lint/suspicious/noExplicitAny: Need to patch prototype methods
    (page as any).__proto__.evaluate = patchEval;

    await (await browser.newPage()).goto('about:blank');

    return scriptsContainer.scripts;
  } finally {
    await browser.close();
  }
}

export async function minifyScripts(scripts: string): Promise<string> {
  const result = await minify(scripts, { toplevel: true });
  return result.code ?? '';
}

export async function generateOutput(
  scripts: string,
  shouldMinify: boolean
): Promise<string> {
  const header = `/*!
 * Note: Auto-generated, do not update manually.
 * Generated by: https://github.com/zorillajs/zorilla/tree/master/packages/extract-stealth-evasions
 * Generated on: ${new Date().toUTCString()}
 * License: MIT
 */
`;

  if (shouldMinify) {
    return header + (await minifyScripts(scripts));
  }

  return header + scripts;
}

export async function writeOutputFile(
  filename: string,
  content: string
): Promise<void> {
  return new Promise((resolve, reject) => {
    fs.writeFile(filename, content, err => {
      if (err) reject(err);
      else resolve();
    });
  });
}

export async function main(args: string[] = process.argv): Promise<void> {
  const options = parseArguments(args);
  const stealthPlugin = stealth();

  if (options.list) {
    console.log(
      'Available evasions:',
      [...stealthPlugin.availableEvasions].join(', ')
    );
    return;
  }

  configureStealthPlugin(stealthPlugin, options);

  const scripts = await extractScripts(stealthPlugin);
  const output = await generateOutput(scripts, options.minify === true);
  const filename = 'stealth' + (options.minify === true ? '.min' : '') + '.js';

  await writeOutputFile(filename, output);

  console.log(`File ${filename} written!`);
  console.log(
    'Included evasions: ',
    [...stealthPlugin.enabledEvasions].join(', ')
  );
}

export function handleError(err: Error): void {
  console.error('Error:', err);
  process.exit(1);
}

export function isMainModule(): boolean {
  return import.meta.url === `file://${process.argv[1]}`;
}

// Only run if this is the main module
/* c8 ignore start */
if (isMainModule()) {
  main().catch(handleError);
}
/* c8 ignore stop */
