name: Extract stealth.min.js

on:
  push:
    branches:
      - main
    paths:
      - 'packages/puppeteer-extra-plugin-stealth/**'
      - 'packages/extract-stealth-evasions/**'
      - '.github/workflows/extract-stealth.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Extract stealth.min.js
        run: |
          cd packages/extract-stealth-evasions
          pnpm exec extract-stealth-evasions
          cp stealth.min.js ../../

      - name: Commit stealth.min.js
        uses: EndBug/add-and-commit@v9
        with:
          add: 'stealth.min.js'
          push: true
          default_author: github_actions
          message: 'Auto-updated stealth.min.js with newest evasions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
